#  _                 ______ _ _ _            
# | |               |  ____(_) | |           
# | |     ___   __ _| |__   _| | |_ ___ _ __ 
# | |    / _ \ / _` |  __| | | | __/ _ \ '__|
# | |___| (_) | (_| | |    | | | ||  __/ |   
# |______\___/ \__, |_|    |_|_|\__\___|_|   
#               __/ |                        
#              |___/     Keep your Log clean!
#

name: LogFilter
version: 0.4
description: Filter log entries and keep your log clean
author: DaAllexx

load: STARTUP
main: de.logfilter.LogFilter

commands:
  logfilter:
    description: Related commands for LogFilter
    aliases: lf
    permission: LogFilter.commands
    permission-message: You don't have permission for \"/logfilter\"
    usage: |
      Command Usage:
      /logfilter <enable/disable> - Enables or disables filtering of log entries

permissions:
  logfilter.*:
    description: Gives access to all LogFilter commands/features
    children:
      logfilter.commands: true
      logfilter.notify: true
  logfilter.commands:
    description: Allows to execute all LogFilter commands
  logfilter.notify:
    description: Sends players messages if plugin updates are available
